#!/usr/bin/env bash

die() {
    echo $*
    exit 1
}

set -e

DEV=$1

echo -n "zpool name: "
read POOL

echo

echo -n "hostname: "
read HOST

echo

echo -n "zfs password: "
read -s POOL_PW
echo

echo -n "      repeat: "
read -s POOL_PW2
echo

echo

echo -n "root password: "
read -s ROOT_PW
echo

echo -n "       repeat: "
read -s ROOT_PW2
echo

if [ $POOL_PW != $POOL_PW2 ]; then
    die "zfs password missmatch"
fi

if [ $ROOT_PW != $ROOT_PW2 ]; then
    die "root password missmatch"
fi

wipefs -a ${DEV}
sed -e 's/\s*\([-+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk ${DEV}
  g     # create gpt table
  n     # new partition
  1     # partition nr 1
        # start at first sector
  -64M  # leave 64M space
  n     # new partition
  2     # partition nr 2
        # start at first free sector
        # take all empty space (64MiB)
  t     # set partition type
  2     # parition nr 2
  1     # set to EFI type
  p     # print partition table
  w     # write partition table to disk
  q     # quit
EOF

wipefs -a ${DEV}1
wipefs -a ${DEV}2

mkfs.vfat -F32 ${DEV}2

zpool create -f -o ashift=12 \
       -O acltype=posixacl -O canmount=off -O compression=lz4 \
       -O dnodesize=auto -O normalization=formD -O relatime=on -O xattr=sa \
       -O mountpoint=/ -R /mnt \
       -O encryption=aes-256-gcm -O keylocation=prompt -O keyformat=passphrase \
       ${POOL} ${DEV}1 << EOF
${POOL_PW}
${POOL_PW}
EOF

zfs set keylocation=file:///etc/zfs/${POOL}.key ${POOL}
zfs create -o mountpoint=none -o canmount=off ${POOL}/ROOT
zfs create -o mountpoint=/ ${POOL}/ROOT/void
zfs create -o mountpoint=/home ${POOL}/home

for i in dev proc sys; do mkdir -p /mnt/$i; mount --rbind /$i /mnt/$i; done
echo y | XBPS_ARCH=x86_64 xbps-install -S -R https://alpha.de.repo.voidlinux.org/current -r /mnt | grep '60:ae:0c:d6:f0:95:17:80:bc:93:46:7a:89:af:a3:2d' >/dev/null || die "invalid repo fingerprint"

XBPS_ARCH=x86_64 xbps-install -Sy -R https://alpha.de.repo.voidlinux.org/current -r /mnt base-system zfs vim efibootmgr refind zfsbootmenu gptfdisk tmux htop

chroot /mnt /bin/bash << CHROOT
echo "${POOL_PW}" > /etc/zfs/${POOL}.key
chmod 0000 /etc/zfs/${POOL}.key

cat << EOF >> /etc/hostname
${HOST}
EOF

cat << EOF >> /etc/resolv.conf
nameserver 1.1.1.1
EOF

cat << EOF >> /etc/rc.conf
KEYMAP="de-latin1"
TIMEZONE="Europe/Berlin"
HARDWARECLOCK="UTC"
EOF

cat << EOF >> /etc/default/libc-locales
en_US.UTF-8 UTF-8
en_US ISO-8859-1
EOF
xbps-reconfigure -f glibc-locales

zpool set cachefile=/etc/zfs/${POOL}.cache ${POOL}
zpool set bootfs=${POOL}/ROOT/void ${POOL}

cat << EOF > /etc/dracut.conf.d/zol.conf
nofsck="yes"
add_dracutmodules+=" zfs "
omit_dracutmodules+=" btrfs "
install_items+=" /etc/zfs/${POOL}.key "
EOF

xbps-reconfigure -f $(xbps-query linux | grep -oP 'linux\d+\.\d+')

zgenhostid

zfs set org.zfsbootmenu:commandline="spl_hostid=$(hostid) ro quiet" ${POOL}/ROOT

cat << EOF >> /etc/fstab
UUID=$(blkid | grep ${DEV}2 | sed -En 's/.*? UUID="([0-9a-zA-Z\-]+)".*/\1/p') /boot/efi vfat defaults,noauto 0 0
EOF
mkdir -p /boot/efi
mount /boot/efi

refind-install
rm /boot/refind_linux.conf

sed -i 's/ManageImages: false/ManageImages: true/' /etc/zfsbootmenu/config.yaml
xbps-reconfigure -f zfsbootmenu

cat << EOF > /boot/efi/EFI/void/refind_linux.conf
"Boot default"  "zfsbootmenu:ROOT=${POOL} spl_hostid=$(hostid) timeout=0 ro quiet loglevel=0"
"Boot to menu"  "zfsbootmenu:ROOT=${POOL} spl_hostid=$(hostid) timeout=-1 ro quiet loglevel=0"
EOF

passwd << EOF
${ROOT_PW}
${ROOT_PW}
EOF

CHROOT

umount -R /mnt
zpool export ${POOL}
